language: smalltalk
sudo: false

# Download sources
before-install: ./loadSources.sh

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-alpha
  - Pharo-stable
  - Pharo-5.0
